<?php
/**
 * Block editor content locking for agent-authored posts.
 *
 * @package Learn
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Enforces content locking in the block editor for posts authored by the agent user.
 *
 * Prevents non-agent users from modifying post_content, post_title, and post_excerpt
 * on agent-authored `learn` posts. Enqueues the editor sidebar feedback panel and
 * displays an informational notice in the block editor.
 */
class Learn_Content_Lock {

	/**
	 * Constructor. Registers all hooks.
	 */
	public function __construct() {
		add_filter( 'wp_insert_post_data', array( $this, 'protect_agent_content' ), 10, 2 );
		add_action( 'enqueue_block_editor_assets', array( $this, 'enqueue_editor_assets' ) );
		add_filter( 'rest_prepare_learn', array( $this, 'add_block_locking' ), 10, 2 );
		add_action( 'enqueue_block_editor_assets', array( $this, 'output_editor_notice' ) );
	}

	/**
	 * Protect agent-authored content from being modified by non-agent users.
	 *
	 * Hooked into `wp_insert_post_data` to restore original values for post_content,
	 * post_title, and post_excerpt when a non-agent user attempts to save changes.
	 *
	 * @param array $data    An array of slashed, sanitized post data.
	 * @param array $postarr An array of sanitized (and slashed) but otherwise unmodified post data.
	 * @return array Filtered post data.
	 */
	public function protect_agent_content( $data, $postarr ) {
		// Only apply to learn post type.
		if ( ! isset( $data['post_type'] ) || 'learn' !== $data['post_type'] ) {
			return $data;
		}

		// Must be an existing post (not a new insert).
		if ( empty( $postarr['ID'] ) ) {
			return $data;
		}

		$post_id      = (int) $postarr['ID'];
		$agent_user_id = $this->get_agent_user_id();

		if ( ! $agent_user_id ) {
			return $data;
		}

		// Check if the post is authored by the agent user.
		$existing_post = get_post( $post_id );

		if ( ! $existing_post || (int) $existing_post->post_author !== (int) $agent_user_id ) {
			return $data;
		}

		// If the current user IS the agent user, allow the change (programmatic updates).
		if ( get_current_user_id() === (int) $agent_user_id ) {
			return $data;
		}

		// Restore protected fields from the existing post.
		$data['post_content'] = $existing_post->post_content;
		$data['post_title']   = $existing_post->post_title;
		$data['post_excerpt'] = $existing_post->post_excerpt;

		return $data;
	}

	/**
	 * Enqueue the editor sidebar script for learn posts authored by the agent user.
	 */
	public function enqueue_editor_assets() {
		$screen = get_current_screen();

		if ( ! $screen || 'learn' !== $screen->post_type ) {
			return;
		}

		$post_id = $this->get_current_post_id();

		if ( ! $post_id || ! $this->is_agent_authored( $post_id ) ) {
			return;
		}

		wp_enqueue_script(
			'1111-learn-editor-sidebar',
			LEARN_PLUGIN_URL . 'admin/js/editor-sidebar.js',
			array( 'wp-plugins', 'wp-edit-post', 'wp-components', 'wp-data', 'wp-element', 'wp-i18n' ),
			LEARN_VERSION,
			true
		);
	}

	/**
	 * Add block locking attributes to REST API responses for learn posts.
	 *
	 * Ensures blocks in agent-authored posts include lock attributes that prevent
	 * moving or removing blocks in the editor.
	 *
	 * @param WP_REST_Response $response The response object.
	 * @param WP_Post          $post     The post object.
	 * @return WP_REST_Response Modified response.
	 */
	public function add_block_locking( $response, $post ) {
		if ( ! $this->is_agent_authored( $post->ID ) ) {
			return $response;
		}

		$data = $response->get_data();

		if ( ! isset( $data['content']['raw'] ) ) {
			return $response;
		}

		$content = $data['content']['raw'];
		$blocks  = parse_blocks( $content );
		$locked  = $this->apply_lock_to_blocks( $blocks );
		$data['content']['raw'] = serialize_blocks( $locked );

		$response->set_data( $data );

		return $response;
	}

	/**
	 * Output an admin notice in the block editor for agent-authored learn posts.
	 *
	 * Uses an inline script that dispatches a notice via the `core/notices` data store.
	 */
	public function output_editor_notice() {
		$screen = get_current_screen();

		if ( ! $screen || 'learn' !== $screen->post_type ) {
			return;
		}

		$post_id = $this->get_current_post_id();

		if ( ! $post_id || ! $this->is_agent_authored( $post_id ) ) {
			return;
		}

		$notice_text = esc_js(
			__( 'This lesson was generated by Learn. Use the feedback panel in the sidebar to request changes.', '1111-learn' )
		);

		wp_add_inline_script(
			'wp-edit-post',
			sprintf(
				'wp.domReady( function() { wp.data.dispatch( "core/notices" ).createNotice( "info", "%s", { isDismissible: true, id: "1111-learn-content-lock-notice" } ); } );',
				$notice_text
			)
		);
	}

	/**
	 * Check whether a post is authored by the agent user.
	 *
	 * @param int $post_id The post ID.
	 * @return bool True if the post is authored by the agent user.
	 */
	private function is_agent_authored( $post_id ) {
		$agent_user_id = $this->get_agent_user_id();

		if ( ! $agent_user_id ) {
			return false;
		}

		$post = get_post( $post_id );

		if ( ! $post ) {
			return false;
		}

		return (int) $post->post_author === (int) $agent_user_id;
	}

	/**
	 * Get the agent user ID from the stored option.
	 *
	 * @return int|false The agent user ID or false if not set.
	 */
	private function get_agent_user_id() {
		return get_option( Learn_Agent_User::OPTION_KEY, false );
	}

	/**
	 * Get the current post ID in the admin context.
	 *
	 * @return int|false The post ID or false if not available.
	 */
	private function get_current_post_id() {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		if ( isset( $_GET['post'] ) ) {
			return absint( $_GET['post'] );
		}

		global $post;

		if ( $post instanceof WP_Post ) {
			return $post->ID;
		}

		return false;
	}

	/**
	 * Recursively apply lock attributes to an array of parsed blocks.
	 *
	 * @param array $blocks Parsed blocks.
	 * @return array Blocks with lock attributes applied.
	 */
	private function apply_lock_to_blocks( $blocks ) {
		foreach ( $blocks as &$block ) {
			if ( empty( $block['blockName'] ) ) {
				continue;
			}

			$block['attrs']['lock'] = array(
				'move'   => true,
				'remove' => true,
			);

			if ( ! empty( $block['innerBlocks'] ) ) {
				$block['innerBlocks'] = $this->apply_lock_to_blocks( $block['innerBlocks'] );
			}
		}

		return $blocks;
	}
}
